---
name: 03 Build With Multi-Platform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set Up Docker BuildX
        uses: docker/setup-buildx-action@v3
      -
        name: Log In To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: $${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Build
        uses: docker/build-push-action@v5
        with:
          push: $${{ github.event_name != 'pull_request' }}
          tags: $${{ secrets.DOCKERHUB_USERNAME }}/docker-ci-automation:03
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7