---
name: 04 Build With Metadata

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  build-image:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log In To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Metadata
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ci-automation
          flavor: |
            latest=false
          tags: |
            type=raw,value=04
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
      -
        name: Docker Build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7