---
name: 05 Build And Comment

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  build-image:
    name: Build Images
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # this permission is needed to create and update comments in PRs
    steps:
      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log In To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Metadata
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ci-automation
          flavor: |
            latest=false
          tags: |
            type=raw,value=05
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
      -
        name: Docker Build
        uses: docker/build-push-action@v5
        with:
          push: false # false for this example to prevent overwriting identical images generated by the previous "04 add metadata" example
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      # this step finds an old comment on a PR, if it exists, so that it can be updated with newer image tags
      -
        name: Find Comment For Image Tags
        uses: peter-evans/find-comment@v3
        if: github.event_name == 'pull_request'
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Docker image tag(s) pushed
      # this step creates a new comment (or updates an old comment) on a PR with image tags that were generated by the docker_metadata step
      -
        name: Create Or Update Comment For Image Tags
        uses: peter-evans/create-or-update-comment@v4
        if: github.event_name == 'pull_request'
        with:
          comment_id: ${{ steps.fc.outputs.comment-id }}
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            Docker image tag(s) pushed:
            ```text
            ${{ steps.docker_metadata.outputs.tags }}
            ```

            Labels added to images
            ```text
            ${{ steps.docker_metadata.outputs.labels}}
            ```
          edit-mode: replace