---
name: 06 Build And Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
    -
      name: Set Up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Log In To Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build And Export To Docker
      uses: docker/build-push-action@v5
      with:
        push: false
        load: true # export to docker engine rather than pushing to a registry
        tags: ${{ github.run_id }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
    -
      name: Run Trivy For All CVEs (Non-Blocking)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ github.run_id }}
        exit-code: 0
        format: table
    -
      name: Docker Metadata For Final Image Build
      id: docker_metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}
        flavor: |
          latest=false
        tags: |
          type=raw,value=06
#          type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
#          type=ref,event=pr
#          type=ref,event=branch
#          type=semver,pattern={{version}}
# the previous lines are commented out so as not to conflict with 04-add-metadata.yml
    -
      name: Docker Build
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.docker_metadata.outputs.tags }}
        labels: ${{ steps.docker_metadata.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64