---
name: 10 Build and Smoke Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Images
    runs-on: ubuntu-latest
    permissions:
      packages: write # Needed to push Docker images to ghcr.io
    steps:
      -
        name: Checkout Git Repo
        uses: actions/checkout@v4
      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log In to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Log In To Github Container Registry (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # Note that the following password uses GITHUB_TOKEN, which is created by default for a workflow on a per-repository basis
          # More information about GITHUB_TOKEN can be found here:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push To Github Container Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.actor }}/docker-ci-automation:${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
      -
        name: Create K3d Kubernetes Cluster
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 1
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
      -
        name: Smoke Test Deployment In K3d Kubernetes
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server=https://ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }}
          export TESTING_IMAGE=ghcr.io/${{ github.actor }}/docker-ci-automation:${{ github.run_id }}
          envsubst < manifests/deployment.yml | kubectl apply -f -
          kubectl rollout status deployment myapp
          kubectl exec deploy/myapp -- curl --fail localhost:8888
      -
        name: Docker Metadata For Final Image Build
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ci-automation,ghcr.io/${{ github.actor }}/docker-ci-automation
          flavor: |
            latest=false
          tags:
            type=raw,value=10
        # the following lines are commented out so as not to conflict with 04-add-metadata.yml
          # type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          # type=ref,event=pr
          # type=ref,event=branch
          # type=semver,pattern={{version}}
      -
        name: Docker Build and Push To Docker Hub and Github Container Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7

